INSERT INTO LEVELTB
    (DIFFICULTY, LENSTART, LENEND, LEVELSCORE)
VALUES
    ('EASY', 4, 5, 3) ;
    
INSERT INTO LEVELTB
    (DIFFICULTY, LENSTART, LENEND, LEVELSCORE)
VALUES
    ('NORMAL', 5, 9, 5) ;
    
INSERT INTO LEVELTB
    (DIFFICULTY, LENSTART, LENEND, LEVELSCORE)
VALUES
    ('HARD', 10, 100, 7) ;